language: node_js
sudo: required
services:
    - docker
install:
    - docker build -t podnoms.azurecr.io/podnoms.web .
before-deploy:
    -  docker login --username=$DOCKER_USER --password=$DOCKER_PASSWORD $DOCKER_HOST
deploy:
    provider: script
    skip_cleanup: true
    script: docker push podnoms.azurecr.io/podnoms.web
    on:
        branch: master
