language: node_js
node_js:
  - "8.10"

branches:
  only:
    - develop

before_script:
  - npm install -g @angular/cli

script:
  - ng build --prod

notifications:
  email:
    on_failure: change
    on_success: change
