version: '2'
services:
  web:
    image: podnoms.azurecr.io/podnoms.api
    ports:
        - "80:80"
        - "443:443"
    links:
        - "api:api"
    volumes:
        - /etc/letsencrypt:/etc/letsencrypt
        - /var/lib/letsencrypt:/var/lib/letsencrypt
  api:
    image: podnoms.azurecr.io/podnoms.api
    container_name: api
    expose:
        - 5000
