version: '2'
services:
  web:
    image: podnoms.azurecr.io/podnoms.web
    container_name: web
    ports:
        - "80:80"
        - "443:443"
    links:
        - "api:api"
    volumes:
        - /etc/letsencrypt:/etc/letsencrypt
        - /var/lib/letsencrypt:/var/lib/letsencrypt
  api:
    image: podnoms.azurecr.io/podnoms.api
    container_name: api
    expose:
        - 5000
  watchtower:
    environment:
         - REPO_USER=${REPO_USER} 
         - REPO_PASS=${REPO_PASS} 

    image: v2tec/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30
