version: 2.0

jobs:
    login:
        steps:
            - setup_remote_docker
            - run: sudo docker login --username=$DOCKER_USER --password=$DOCKER_PASSWORD $DOCKER_HOST

    build:
        machine: true
        steps:
            - checkout
            - setup_remote_docker
            - run: sudo docker build -t podnoms.azurecr.io/podnoms.web .

    deploy:
        machine: true
        steps:
            - setup_remote_docker
            - run: sudo docker push podnoms.azurecr.io/podnoms.web
workflows:
    version: 2
    commit:
        jobs:
            - login
            - checkout:
                requires:
                  - login
            - build:
                requires:
                  - checkout
                filters:
                    branches:
                      only: master

