sudo: required
services:
    docker

version: 3
general:
  branches:
    only:
      - master
jobs:
 build:
    include:
        - stage: build
            - checkout

                docker info
                docker build -t $REGISTRY_HOST/podnoms.web .
                docker login --username=$DOCKER_USER --password=$DOCKER_PASSWORD $REGISTRY_HOST
                docker tag podnoms.web $REGISTRY_HOST/podnoms.web
                docker push $REGISTRY_HOST/podnoms.web

        - test: build
        - debloy: build
