machine:
  services:
    - docker

dependencies:
  override:
    - docker info
    - docker build --rm=false -t $REGISTRY_HOST/podnoms-web .

test:
  override:
    - docker run -d hello-world

deployment:
  hub:
    branch: master
    commands:
      - docker login -e $DOCKER_USER -u $DOCKER_USER -p $DOCKER_PASSWORD $REGISTRY_HOST
      - docker push $REGISTRY_HOST/circleci
