version: 2.0

jobs:
    login:
        docker:
          - image: circleci/classic:201708-01
        steps:
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD $DOCKER_HOST

    build:
        docker:
          - image: circleci/classic:201708-01
        steps:
            - checkout
            - run: docker build -t podnoms.azurecr.io/podnoms.web .

    deploy:
        docker:
          - image: circleci/classic:201708-01
        steps:
            - run: docker push podnoms.azurecr.io/podnoms.web
workflows:
    version: 2
    commit:
        jobs:
            - login
            - checkout:
                requires:
                  - login
            - build:
                requires:
                  - checkout
                filters:
                    branches:
                      only: master

