version: 2.0
defaults: &defaults
  working_directory: ~/app
  docker:
    # the Docker image with Cypress dependencies
    - image: debian
      environment:
        ## this enables colors in the output
        TERM: xterm
jobs:
    login:
        machine: true
        steps:
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD $DOCKER_HOST

    build:
        machine: true
        steps:
            - checkout
            - run: docker build -t podnoms.azurecr.io/podnoms.web .

    deploy:
        machine: true
        steps:
            - run: docker push podnoms.azurecr.io/podnoms.web
workflows:
    version: 2
    commit:
        jobs:
            - login
            - checkout:
                requires:
                  - login
            - build:
                requires:
                  - checkout
                filters:
                    branches:
                      only: master

