name: CI to Azure Container Registry
on:
  push:
    branches: [ feature/github_actions ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2

    - name: Login to Docker Hub
    - uses: azure/docker-login@v1
      with:
        login-server: mycontainer.azurecr.io
        username: ${{ secrets.AKR_USER }}
        password: ${{ secrets.AKR_PASSWORD }}

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        push: true
        tags: podnoms.azurecr.io/podnoms.web:latest

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
